[build]
  command = "npm run build -w @tinynotes/web"
  publish = "apps/web/dist"

[[redirects]]
  from = "/api/*"
  to = "https://tinynotes-app-api.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
