[build]
  command = "npm run build -w @tinynotes/web"
  publish = "apps/web/dist"

[[headers]]
  for = "/assets/*"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/*"
  to = "https://tinynotes-app-api.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
